version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/html/
  - source: /tmp/wp_config.php
    destination: /var/www/html/wp_config.php
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: apache
    group: apache
    mode: 644
    type:
      - file  
hooks:
  BeforeBlockTraffic:
   - location: ./stop_httpd.sh
     timeout: 600
     runas: root 
  AfterInstall:
   - location: ./start_httpd.sh
     timeout: 600
     runas: root 
